# Generated by Django 5.0.6 on 2024-07-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0005_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(default='Comment Title', max_length=100),
        ),
    ]
